version: '3'

services:
  edu:
    image: envionapi
    container_name: envionapi
    ports:
      - 8001:8080
    environment:
      - RPC_ENDPOINT=https://mainnet.infura.io/3l5dxBOP3wPspnRDdG1u


  unit:
    image: golang:1.8
    volumes:
      - .:/usr/src/myapp
      - ~/sd/go:/go
    working_dir: /usr/src/myapp
    command: bash -c "go get -d -v -t && go build -v -o index"


